import React from 'react';
import { SlidersHorizontal, CheckCircle2, ShieldCheck, Box, Activity } from 'lucide-react';
export const NPanelInspector = ({ selectedObject, statistics, currentStep, }) => {
    return (React.createElement("div", { className: "flex flex-col h-full bg-slate-900 border-l border-slate-800 text-slate-200 select-none overflow-y-auto" },
        React.createElement("div", { className: "flex items-center justify-between px-3 py-2 border-b border-slate-800 bg-slate-900/90" },
            React.createElement("div", { className: "flex items-center gap-1.5 text-xs font-semibold tracking-wide text-slate-300" },
                React.createElement(SlidersHorizontal, { className: "w-3.5 h-3.5 text-sky-400" }),
                React.createElement("span", null, "\u5C5E\u6027\u4E0E\u53C2\u6570\u68C0\u9A8C (N-Panel)")),
            React.createElement("span", { className: "text-[10px] bg-sky-950 text-sky-300 border border-sky-800 px-1.5 py-0.5 rounded font-mono" }, "\u6309 [N] \u952E\u9762\u677F")),
        React.createElement("div", { className: "p-3 space-y-3 flex-1 text-xs" },
            selectedObject ? (React.createElement(React.Fragment, null,
                React.createElement("div", { className: "bg-slate-950/80 p-2.5 rounded-lg border border-slate-800 space-y-1" },
                    React.createElement("div", { className: "flex items-center justify-between" },
                        React.createElement("span", { className: "text-slate-400 text-[11px]" }, "\u7269\u4F53\u540D\u79F0 (Item Name)"),
                        React.createElement("span", { className: "text-[10px] bg-slate-800 text-slate-300 px-1.5 py-0.5 rounded font-mono" }, selectedObject.collection)),
                    React.createElement("div", { className: "text-sm font-bold text-sky-400 font-mono" }, selectedObject.name),
                    React.createElement("div", { className: "text-[11px] text-slate-400" }, selectedObject.description)),
                React.createElement("div", { className: "bg-slate-950/80 p-2.5 rounded-lg border border-slate-800 space-y-2" },
                    React.createElement("div", { className: "text-[11px] font-semibold text-slate-300 flex items-center justify-between" },
                        React.createElement("span", null, "\u5750\u6807\u53D8\u6362 (Transform)"),
                        React.createElement("span", { className: "text-[10px] text-emerald-400 font-mono" }, "\u5355\u4F4D: \u7C73 (m)")),
                    React.createElement("div", { className: "space-y-1" },
                        React.createElement("div", { className: "text-[10px] text-slate-400" }, "\u4F4D\u7F6E (Location):"),
                        React.createElement("div", { className: "grid grid-cols-3 gap-1 font-mono text-[11px]" },
                            React.createElement("div", { className: "bg-slate-900 px-2 py-1 rounded border border-slate-800/80 flex items-center justify-between" },
                                React.createElement("span", { className: "text-red-400" }, "X"),
                                React.createElement("span", null,
                                    selectedObject.position.x.toFixed(2),
                                    "m")),
                            React.createElement("div", { className: "bg-slate-900 px-2 py-1 rounded border border-slate-800/80 flex items-center justify-between" },
                                React.createElement("span", { className: "text-green-400" }, "Y"),
                                React.createElement("span", null,
                                    selectedObject.position.y.toFixed(2),
                                    "m")),
                            React.createElement("div", { className: "bg-slate-900 px-2 py-1 rounded border border-slate-800/80 flex items-center justify-between" },
                                React.createElement("span", { className: "text-blue-400" }, "Z"),
                                React.createElement("span", null,
                                    selectedObject.position.z.toFixed(2),
                                    "m")))),
                    React.createElement("div", { className: "space-y-1" },
                        React.createElement("div", { className: "text-[10px] text-slate-400" }, "\u5B9E\u9645\u51E0\u4F55\u5C3A\u5BF8 (Dimensions):"),
                        React.createElement("div", { className: "grid grid-cols-3 gap-1 font-mono text-[11px]" },
                            React.createElement("div", { className: "bg-slate-900 px-2 py-1 rounded border border-slate-800/80 flex items-center justify-between" },
                                React.createElement("span", { className: "text-red-400" }, "\u957F"),
                                React.createElement("span", null,
                                    selectedObject.dimensions.x.toFixed(1),
                                    "m")),
                            React.createElement("div", { className: "bg-slate-900 px-2 py-1 rounded border border-slate-800/80 flex items-center justify-between" },
                                React.createElement("span", { className: "text-green-400" }, "\u9AD8"),
                                React.createElement("span", null,
                                    selectedObject.dimensions.y.toFixed(2),
                                    "m")),
                            React.createElement("div", { className: "bg-slate-900 px-2 py-1 rounded border border-slate-800/80 flex items-center justify-between" },
                                React.createElement("span", { className: "text-blue-400" }, "\u5BBD"),
                                React.createElement("span", null,
                                    selectedObject.dimensions.z.toFixed(1),
                                    "m"))))),
                React.createElement("div", { className: "bg-slate-950/80 p-2.5 rounded-lg border border-slate-800 space-y-2" },
                    React.createElement("div", { className: "text-[11px] font-semibold text-slate-300" }, "\u6750\u8D28\u69FD\u4E0E\u6E32\u67D3\u53C2\u6570 (Material Properties)"),
                    React.createElement("div", { className: "flex items-center gap-2 p-1.5 bg-slate-900 rounded border border-slate-800" },
                        React.createElement("span", { className: "w-5 h-5 rounded border border-slate-700 shadow-inner shrink-0", style: { backgroundColor: selectedObject.materialColor } }),
                        React.createElement("div", { className: "flex-1 min-w-0 font-mono text-[11px]" },
                            React.createElement("div", { className: "text-slate-200 truncate" }, selectedObject.materialName),
                            React.createElement("div", { className: "text-slate-400 text-[10px]" },
                                "\u8272\u503C: ",
                                selectedObject.materialColor))),
                    React.createElement("div", { className: "grid grid-cols-2 gap-2 text-[11px]" },
                        React.createElement("div", { className: "bg-slate-900 p-1.5 rounded border border-slate-800" },
                            React.createElement("span", { className: "text-slate-400 text-[10px]" }, "\u7C97\u7CD9\u5EA6 (Roughness):"),
                            React.createElement("div", { className: "font-mono text-slate-200 font-semibold" }, selectedObject.roughness)),
                        React.createElement("div", { className: "bg-slate-900 p-1.5 rounded border border-slate-800" },
                            React.createElement("span", { className: "text-slate-400 text-[10px]" }, "\u91D1\u5C5E\u5EA6 (Metallic):"),
                            React.createElement("div", { className: "font-mono text-slate-200 font-semibold" }, selectedObject.metallic ?? 0.05)))))) : (React.createElement("div", { className: "bg-slate-950/50 p-4 rounded-lg border border-dashed border-slate-800 text-center space-y-2" },
                React.createElement(Box, { className: "w-8 h-8 text-slate-600 mx-auto" }),
                React.createElement("div", { className: "text-slate-300 font-medium" }, "\u8BF7\u5728 3D \u89C6\u56FE\u4E2D\u70B9\u51FB\u6A21\u578B\u5BF9\u8C61"),
                React.createElement("div", { className: "text-[11px] text-slate-400 leading-relaxed" }, "\u652F\u6301\u70B9\u51FB\u4E3B\u529E\u516C\u697C\u3001\u73AF\u8DEF\u3001\u505C\u8F66\u573A\u3001\u56F4\u5899\u3001\u5927\u95E8\u3001\u50A8\u80FD\u96C6\u88C5\u7BB1\u673A\u7EC4\u3001\u8DEF\u706F\u6216\u5341\u5B57\u9762\u7247\u6811\uFF0C\u5B9E\u65F6\u68C0\u9A8C\u624B\u518C\u5BF9\u5E94\u5C3A\u5BF8\u4E0E\u516C\u5DEE\u3002"))),
            React.createElement("div", { className: "bg-slate-950/80 p-2.5 rounded-lg border border-slate-800 space-y-2" },
                React.createElement("div", { className: "flex items-center justify-between text-[11px] font-semibold text-slate-300" },
                    React.createElement("div", { className: "flex items-center gap-1.5" },
                        React.createElement(Activity, { className: "w-3.5 h-3.5 text-emerald-400" }),
                        React.createElement("span", null, "\u9762\u6570\u4E0E\u62D3\u6251\u7EDF\u8BA1 (\u7B2C 47 \u6B65)")),
                    React.createElement("span", { className: "text-[10px] text-emerald-400 flex items-center gap-1" },
                        React.createElement(CheckCircle2, { className: "w-3 h-3" }),
                        "\u5BA1\u6838\u8FBE\u6807")),
                React.createElement("div", { className: "grid grid-cols-3 gap-1.5 font-mono text-[11px]" },
                    React.createElement("div", { className: "bg-slate-900 p-1.5 rounded border border-slate-800 text-center" },
                        React.createElement("div", { className: "text-[10px] text-slate-400" }, "\u9876\u70B9 (Verts)"),
                        React.createElement("div", { className: "text-sky-300 font-bold" }, statistics.verts.toLocaleString())),
                    React.createElement("div", { className: "bg-slate-900 p-1.5 rounded border border-slate-800 text-center" },
                        React.createElement("div", { className: "text-[10px] text-slate-400" }, "\u9762\u6570 (Faces)"),
                        React.createElement("div", { className: "text-sky-300 font-bold" }, statistics.faces.toLocaleString())),
                    React.createElement("div", { className: "bg-slate-900 p-1.5 rounded border border-slate-800 text-center" },
                        React.createElement("div", { className: "text-[10px] text-slate-400" }, "\u4E09\u89D2\u9762 (Tris)"),
                        React.createElement("div", { className: "text-emerald-400 font-bold" }, statistics.tris.toLocaleString()))),
                React.createElement("div", { className: "space-y-1" },
                    React.createElement("div", { className: "flex items-center justify-between text-[10px] text-slate-400" },
                        React.createElement("span", null, "\u603B\u9762\u6570\u9884\u7B97 (\u4E0A\u9650 \u2264 300,000 Tris):"),
                        React.createElement("span", { className: "font-mono text-emerald-400" },
                            ((statistics.tris / statistics.maxTrisLimit) * 100).toFixed(2),
                            "%")),
                    React.createElement("div", { className: "w-full h-1.5 bg-slate-900 rounded-full overflow-hidden border border-slate-800" },
                        React.createElement("div", { className: "h-full bg-emerald-500 rounded-full", style: {
                                width: `${Math.max(1, (statistics.tris / statistics.maxTrisLimit) * 100)}%`,
                            } }))),
                React.createElement("div", { className: "text-[10px] text-slate-400 bg-emerald-950/30 border border-emerald-900/50 p-1.5 rounded flex items-center gap-1.5" },
                    React.createElement(ShieldCheck, { className: "w-3.5 h-3.5 text-emerald-400 shrink-0" }),
                    React.createElement("span", null, "\u8F7B\u91CF\u5316\u6781\u81F4\u4F18\u5316\u5DF2\u5B8C\u6210\uFF1A\u8FDC\u4F4E\u4E8E 30 \u4E07\u9762\u6027\u80FD\u9608\u503C\uFF0C\u4E1D\u6ED1\u9002\u914D Web \u4E0E\u79FB\u52A8\u5B6A\u751F\u3002")))),
        React.createElement("div", { className: "p-2.5 border-t border-slate-800 bg-slate-950 text-[11px] text-slate-400 flex items-center justify-between" },
            React.createElement("span", null, "\u5F53\u524D\u5EFA\u9020\u8FDB\u5EA6"),
            React.createElement("span", { className: "text-sky-400 font-mono" },
                "\u7B2C ",
                currentStep,
                " / 54 \u6B65"))));
};
